### ISSUE TITLE
icc_beta throws error: "Mat::row(): index out of bounds"

### ISSUE THREAD

**Issue by franciscowilhelm** [tmsalab/iccbeta#3]
The icc_beta threw the following error: 

```
error: Mat::row(): index out of bounds
Error in icc_beta(X, df_icc[, "L2id"], T1, vy) : 
  Mat::row(): index out of bounds
```

I just tried to calculate the icc_beta for a dataset with the following structure:
I have a dataset where L1 = time point, L2 = person. Each L2 unit has several L1 units.

However, 
- the L1 are not equal between L2 (different group sizes). 
- and sometimes persons skipped time points, resulting in cases where L1 may be NA for, say, L1id 1, 2, 3, but have a value for L1id 4,5,6. In such cases, the L1id rows 1,2,3 are retained, even if NA for the Y variable.

My hunch is that this data structure leads to the aforementioned error. Specifically, `df_icc[, "L2id"]` is `444`, whereas `nrow(X)` is `297`.

**Comment by steveculpepper** [comment]
That’s right. We did not write the function to remove cases with missing data. It should work once you omit those observations.

Sent from my iPhone

On Jan 28, 2019, at 07:49, franciscowilhelm <notifications@github.com<mailto:notifications@github.com>> wrote:


The icc_beta threw the following error:

error: Mat::row(): index out of bounds
Error in icc_beta(X, df_icc[, "L2id"], T1, vy) :
  Mat::row(): index out of bounds


I just tried to calculate the icc_beta for a dataset with the following structure:
I have a dataset where L1 = time point, L2 = person. Each L2 unit has several L1 units.

However,

  *   the L1 are not equal between L2 (different group sizes).
  *   and sometimes persons skipped time points, resulting in cases where L1 may be NA for, say, L1id 1, 2, 3, but have a value for L1id 4,5,6.

My hunch is that this data structure leads to the aforementioned error. Specifically, df_icc[, "L2id"] is 444, whereas nrow(X) is 297.

**Comment by franciscowilhelm** [comment]
Thanks! It works fine after removing :)
Should you do plan to update at some point, I suggest having a more specific error message because I think its a rather common occurence.

**Comment by coatless** [comment]
@franciscowilhelm thanks for the feedback. 

We've incorporated a check for missing values in `X` within the routine. We'll likely try to push an update to CRAN tomorrow.

**Comment by franciscowilhelm** [comment]
> @franciscowilhelm thanks for the feedback.
> 
> We've incorporated a check for missing values in `X` within the routine. We'll likely try to push an update to CRAN tomorrow.

Thanks for the fast response! I noticed one can get the l2id vector from the lmerMod object, e.g. `lmm1@frame$id`.

**Comment by coatless** [comment]
@franciscowilhelm great point. I've opened a new issue (c.f. #5)  to track just passing a `lmer` model object into the `icc_beta()` function.
