### ISSUE TITLE
Create S3 object for `icc_beta()` to allow for direct `lmer` model use

### ISSUE THREAD

**Issue by coatless** [tmsalab/iccbeta#5]
Instead of forcing the user to decompose the model, we'll retrieve the model components automatically and, then, compute the icc.

**Comment by coatless** [comment]
Finished in #6

**Comment by coatless** [comment]
@franciscowilhelm

Could you give these two changes a go? Please use:

```r
if(!requireNamespace("devtools")) install.packages("devtools")
devtools::install_github("tmsalab/iccbeta")
```

Note: This requires a compiler.

**Comment by coatless** [comment]
@franciscowilhelm scratch that. You can try out the new version of `iccbeta` directly from CRAN. c.f.

```r
install.packages("iccbeta")
```

**Comment by franciscowilhelm** [comment]
> @franciscowilhelm scratch that. You can try out the new version of `iccbeta` directly from CRAN. c.f.
> 
> ```r
> install.packages("iccbeta")
> ```

@coatless Package on CRAN is not yet compiled, and fails to compile on my Macbook (`clang: error: unsupported option '-fopenmp'`). I'll check again when CRAN compiling is done!

**Comment by coatless** [comment]
@franciscowilhelm the binary for macOS was just now created by CRAN. Let me know what you think of the v1.2.0 version.

**Comment by franciscowilhelm** [comment]
> @franciscowilhelm the binary for macOS was just now created by CRAN. Let me know what you think of the v1.2.0 version.

Just passing the lmer object is _very_ convenient! Thanks for the update. I hope this will induce more people to do power analyses of this sort.
